---
title: "Replication of Study X by Sample & Sample (20xx, Psychological Science)"
author: "Replication Author[s] (contact information)"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
  html:
    toc: true
    toc_depth: 3
---

<!-- Replication reports should all use this template to standardize reporting across projects.  These reports will be public supplementary materials that accompany the summary report(s) of the aggregate results. -->

## Introduction

Polite speech poses a challenge for assumptions about communication as accurate and efficient information transfer in both classical Gricean pragmatics and more recent probabilistic pragmatics frameworks. For the sake of being polite, speakers opt for utterances that are indirect, underinformative, and sometimes even irrelevant or untruthful. To account for how polite speech arises, Yoon et al. (2020) propose a probabilistic cognitive model which is based on the Rational Speech Act (RSA) framework and incorporates three different informational and social utilities into its machinery. They hypothesize that underlying a speaker’s polite language use is a competition between three goals: to be informative, to be kind (to save the listener’s face), and to present oneself in a good light – quantitatively formalized as three separate weighted utilities (informational, prosocial, and self-presentational) contributing to the total utterance utility. Crucially, the model predictions and behavioral results converge on the following polite speech pattern: when describing a bad state, a speaker whose goal is to be both informative and kind would produce more indirect, negated utterances - saying, for example, that something is "not bad" or "not terrible" even though they actually feel much more negatively about it. This replication project aims to reproduce this key finding in Yoon et al.'s (2020) production experiment.


## Methods

### Power Analysis
Yoon et al. (2020) analyzed behavioral data from 202 participants in their production experiment using a Bayesian mixed-effects model. The model revealed strong interaction effects between true state and the speaker's goal with tight 95% Bayesian credible intervals that did not include zero: In worse states, speakers whose goal was to be both informative and kind produced more negation than speakers whose goal was only to be informative (95% Bayesian CI: [−1.69, −0.98]) or only to be kind (95% Bayesian CI: [−0.92, −0.07]). 


### Planned Sample

Given those statistically robust effects found in the original study with 202 participants and the relatively low number of trials per participant, I plan to use a matching sample size of 202. Using the same sample size would also facilitate a more direct, one-to-one comparison of the observed effects between the original and replication study.

### Materials

The experiment has a 4x3 factorial design: true state (0, 1, 2, 3 hearts) and speaker’s goal (informative, kind, both). Each participant is given 12 context items depicting each of the 12 conditions in randomized order. In every context item, the speaker is supposed to tell the listener what they think about something the listener created. The list from which the listener's creative work is drawn for each context item includes: "poem","cake","cookie","presentation","song","film","solo","monologue","dance","painting","app","review", "recital". The speaker's goal and task prompt for participants are given in the form of a conditional question that reads: “If [speaker's name] wanted to make [listener's name] feel good but not necessarily give accurate and informative feedback (or give accurate and informative feedback but not necessarily make [listener's name] feel good, or BOTH make [listener's name] feel good AND give accurate and informative feedback), what would [speaker's name] be most likely to say?”

### Procedure	

First, participants read a scenario where person A doesn’t know how good their creative work is and asks for person B’s opinion on it. Then, they are given 2 pieces of information: (i) how B truly feels about A’s creative work shown as a number of red hearts, and (ii) what B’s goal in communicating an answer to A is
Finally, they are asked to indicate what person B would most likely say given those two pieces of information. Formula for indicating person B’s most likely production: It + was/wasn’t (chosen from a dropdown menu) + terrible/bad/good/amazing (chosen from a dropdown menu). 


### Analysis Plan

I plan to analyze the data using a Bayesian mixed-effects model following Yoon et al.'s (2020) analysis script.

**Clarify key analysis of interest here**  You can also pre-specify additional analyses you plan to do.

### Differences from Original Study

Explicitly describe known differences in sample, setting, procedure, and analysis plan from original study.  The goal, of course, is to minimize those differences, but differences will inevitably occur.  Also, note whether such differences are anticipated to make a difference based on claims in the original article or subsequent published research on the conditions for obtaining the effect.

### Methods Addendum (Post Data Collection)

You can comment this section out prior to final report with data collection.

#### Actual Sample
  Sample size, demographics, data exclusions based on rules spelled out in analysis plan

#### Differences from pre-data collection methods plan
  Any differences from what was described as the original plan, or “none”.


## Results


### Data preparation

Data preparation following the analysis plan.
	
```{r include=F}
### Data Preparation

#### Load Relevant Libraries and Functions

#### Import data

#### Data exclusion / filtering

#### Prepare data for analysis - create columns etc.
```

### Confirmatory analysis

The analyses as specified in the analysis plan.  

*Side-by-side graph with original graph is ideal here*

### Exploratory analyses

Any follow-up analyses desired (not required).  

## Discussion

### Summary of Replication Attempt

Open the discussion section with a paragraph summarizing the primary result from the confirmatory analysis and the assessment of whether it replicated, partially replicated, or failed to replicate the original result.  

### Commentary

Add open-ended commentary (if any) reflecting (a) insights from follow-up exploratory analysis, (b) assessment of the meaning of the replication (or not) - e.g., for a failure to replicate, are the differences between original and present study ones that definitely, plausibly, or are unlikely to have been moderators of the result, and (c) discussion of any objections or challenges raised by the current and original authors about the replication attempt.  None of these need to be long.
